In [1]:
print("omg jupyter")

omg jupyter


In [3]:
import numpy as np

In [4]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [7]:
a=np.array([(1,2,3), (4,5,6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

##Numpy Operations

In [8]:
a=np.array([(1,2,3), (4,5,6)])
a.ndim

2

In [25]:
a=np.array([["C", "H", "R"],
            ["banana", "strawberry", "I"],
            ["S","orange","kiwi"]])

word=a[0,0] + a[0,1] + a[0,2] + a[1,2] + a[2,0]
print(word)


CHRIS


In [9]:
import numpy as np

a=np.array([[2,3,4,5], 
            [7,5,4,3], 
            [6,9,10,11] , 
            [15,17,89,29]])

#array[start:end:step]1

print(a[0:4:2])

[[ 2  3  4  5]
 [ 6  9 10 11]]
